const M=[['clients','Клиенты','Clients'],['orders','Заказы','Orders'],['repairs','Ремонты','Repairs'],['services','Услуги и цены','Services & prices'],['inventory','Склад и запчасти','Inventory & parts'],['suppliers','Поставщики','Suppliers'],['docs','Документы','Documents'],['tasks','Задачи','Tasks'],['finance','Финансы','Finance'],['notify','Уведомления','Notifications'],['reports','Отчёты','Reports'],['history','История','History'],['settingspage','Настройки','Settings']];
const L={ru:{home:'Главная',current:'Текущие задачи',new:'Новый ремонт',inv:'Склад/поставщики',free:'Свободная зона',find:'Найти или начать действие',photo:'Фото',qr:'QR',search:'Поиск',voice:'Голос',added:'Уже добавлено',missing:'Нужно уточнить',create:'Создать заказ',start:'Начать ремонт'},en:{home:'Home',current:'Current tasks',new:'New repair',inv:'Inventory/Suppliers',free:'Free area',find:'Find or start action',photo:'Photo',qr:'QR',search:'Search',voice:'Voice',added:'Added',missing:'Need to clarify',create:'Create order',start:'Start repair'}};
const S={page:localStorage.bw_page||'home',lang:localStorage.bw_lang||'ru',theme:localStorage.bw_theme||'dark',scale:+(localStorage.bw_scale||1),widgets:JSON.parse(localStorage.bw_widgets||'[]'),draft:JSON.parse(localStorage.bw_draft||'{}')};
const $=id=>document.getElementById(id), tr=k=>L[S.lang][k]||k, ml=id=>{let m=M.find(x=>x[0]===id);return S.lang==='ru'?m[1]:m[2]};
function save(){localStorage.bw_page=S.page;localStorage.bw_lang=S.lang;localStorage.bw_theme=S.theme;localStorage.bw_scale=S.scale;localStorage.bw_widgets=JSON.stringify(S.widgets);localStorage.bw_draft=JSON.stringify(S.draft)}
function prefs(){document.body.classList.toggle('dark',S.theme==='dark');document.documentElement.style.setProperty('--scale',S.scale);$('range').value=S.scale;$('lightB').classList.toggle('active',S.theme==='light');$('darkB').classList.toggle('active',S.theme==='dark');$('ruB').classList.toggle('active',S.lang==='ru');$('enB').classList.toggle('active',S.lang==='en')}
function top(t){return `<div class="top"><button class="icon" data-menu>≡</button><div class="title">${t}</div><button class="icon" data-settings>⚙</button><button class="icon" data-home>⌂</button></div>`}
function home(){ $('home').innerHTML=`${top(tr('home'))}<div class="label">${tr('current')}</div><div class="box"><div class="row" data-go="tasks"><b>№12541 · ${S.lang==='ru'?'Ожидает оплату':'Waiting payment'}</b><span>${S.lang==='ru'?'Иванов Сергей · 8 900 ₽':'Ivanov Sergey · 8 900 ₽'}</span></div><div class="row" data-go="inventory"><b>${S.lang==='ru'?'Нужна запчасть для iPhone 15 Pro':'Part needed for iPhone 15 Pro'}</b><span>${S.lang==='ru'?'Открыть склад':'Open inventory'}</span></div></div><div class="action" data-empty>${tr('new')}</div><div class="action" data-go="inventory">${tr('inv')}</div><div class="label">${tr('free')}</div><div id="zone" class="box zone"></div>`; widgets() }
function generic(id){let title=ml(id),body=`<div class="box"><div class="row" data-sheet><b>${tr('find')}</b><span>${S.lang==='ru'?'Открыть нижнюю панель':'Open bottom panel'}</span></div><div class="row"><b>${title}</b><span>${S.lang==='ru'?'Схематичная страница':'Wireframe page'}</span></div></div>`;
 if(id==='clients')body=`<div class="box"><div class="row" data-client><b>${S.lang==='ru'?'Иванов Сергей':'Ivanov Sergey'}</b><span>+7 999 123-45-67 · ${tr('start')}</span></div><div class="row"><b>${S.lang==='ru'?'Петров Игорь':'Petrov Igor'}</b><span>${S.lang==='ru'?'Карточка клиента':'Customer card'}</span></div></div>`;
 if(id==='inventory')body=`<div class="box"><div class="row" data-part="Дисплей iPhone 15 Pro|6 450 ₽ · Supplier B"><b>${S.lang==='ru'?'Дисплей iPhone 15 Pro':'iPhone 15 Pro Display'}</b><span>${S.lang==='ru'?'Добавить в ремонт':'Add to repair'}</span></div><div class="row" data-part="Original Pull iPhone 15 Pro|8 200 ₽ · Supplier A"><b>Original Pull iPhone 15 Pro</b><span>${S.lang==='ru'?'Добавить в ремонт':'Add to repair'}</span></div></div>`;
 if(id==='orders')body=`<div class="box"><div class="row"><b>№12541 · ${S.lang==='ru'?'Иванов Сергей':'Ivanov Sergey'}</b><span>${S.lang==='ru'?'Существующий заказ':'Existing order'}</span></div><div class="row"><b>№12552 · ${S.lang==='ru'?'Петров Игорь':'Petrov Igor'}</b><span>${S.lang==='ru'?'Существующий заказ':'Existing order'}</span></div></div>`;
 $(id).innerHTML=top(title)+body
}
function draft(){let d=S.draft,k=[],n=[];if(d.customer)k.push(['Клиент',d.customer]);if(d.phone)k.push([S.lang==='ru'?'Телефон':'Phone',d.phone]);if(d.model)k.push([S.lang==='ru'?'Модель':'Model',d.model]);if(d.issue)k.push([S.lang==='ru'?'Проблема':'Issue',d.issue]);if(d.part)k.push([S.lang==='ru'?'Запчасть':'Part',d.part]);if(d.price)k.push([S.lang==='ru'?'Цена / поставщик':'Price / supplier',d.price]);if(!d.customer)n.push(['customer',S.lang==='ru'?'Добавить клиента':'Add customer']);if(!d.model)n.push(['model',S.lang==='ru'?'Добавить модель':'Add model']);if(!d.issue)n.push(['issue',S.lang==='ru'?'Добавить проблему':'Add issue']);$('newrepair').innerHTML=`${top(tr('new'))}<div class="label">${tr('added')}</div><div class="box draft">${k.length?k.map(x=>`<div class="row"><b>${x[0]}</b><span>${x[1]}</span></div>`).join(''):`<div class="row"><b>${S.lang==='ru'?'Пока пусто':'Nothing yet'}</b></div>`}</div><div class="label">${tr('missing')}</div><div class="box draft">${n.length?n.map(x=>`<div class="need" data-add="${x[0]}">${x[1]}</div>`).join(''):`<div class="row"><b>${S.lang==='ru'?'Минимум данных заполнен':'Minimum data completed'}</b></div>`}</div><button class="primary" ${n.length?'disabled':''} data-create>${tr('create')}</button>`}
function render(){home();M.forEach(x=>generic(x[0]));draft();menu();prefs();go(S.page,false)}
function go(id,rer=true){S.page=id;save();document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));$(id).classList.add('on');hideRight();hideLeft();if(rer){if(id==='home')home();if(id==='newrepair')draft()}bind()}
