const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const store={get(k,f){try{return localStorage.getItem(k)||f}catch{return f}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
const orders=[
{id:'#A-10234',tag:'В работе',client:'Иван Петров',phone:'+7 900 123-45-67',device:'iPhone 14 Pro',meta:'256 GB, Deep Purple',problem:'Разбит экран',problemMeta:'Нет изображения',amount:'24 500 ₽',stage:1},
{id:'#A-10233',tag:'Диагностика',client:'Анна Кузнецова',phone:'+7 912 444-09-12',device:'Samsung S23',meta:'128 GB, Phantom Black',problem:'Не заряжается',problemMeta:'Проверка разъёма и АКБ',amount:'3 500 ₽',stage:2},
{id:'#A-10232',tag:'К выдаче',client:'Сергей Дмитриев',phone:'+7 922 018-22-44',device:'iPhone 11',meta:'128 GB, Black',problem:'Замена аккумулятора',problemMeta:'ОТК пройден',amount:'6 490 ₽',stage:6}
];
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),1700)}
function updateClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}updateClock();setInterval(updateClock,30000);
function setTheme(theme){document.documentElement.dataset.theme=theme;store.set('aion.comfort.v5.theme',theme);document.querySelector('meta[name="theme-color"]').setAttribute('content',theme==='light'?'#eef3fb':'#030713');$('#themeIcon').innerHTML=theme==='light'?'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.66 6.34l1.41-1.41"/>':'<path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z"/>'}
setTheme(store.get('aion.comfort.v5.theme','dark'));$('#themeBtn').addEventListener('click',()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';setTheme(t);toast(t==='light'?'Светлая тема включена':'Тёмная тема включена')});
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('.nav[data-view-target]').forEach(n=>n.classList.toggle('active',n.dataset.viewTarget===name));window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});store.set('aion.comfort.v5.view',name)}
$$('[data-view-target]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewTarget)));showView(store.get('aion.comfort.v5.view','home'));
$$('[data-toast]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.toast)));$('#quickBtn').addEventListener('click',()=>toast('Быстрый доступ: новый ремонт, поиск и выдача'));$('#bellBtn').addEventListener('click',()=>toast('3 уведомления: выдача, оплата и просроченная задача'));$('#profileBtn').addEventListener('click',()=>toast('Профиль Максима — демо'));$('#eveBtn').addEventListener('click',()=>{toast('EvE открывает следующий безопасный шаг');showView('home');setTimeout(()=>document.querySelector('[data-order="2"]').click(),100)});
function selectOrder(i){const o=orders[i];$$('.order-card').forEach((c,n)=>c.classList.toggle('active',n===i));$('#currentId').textContent=o.id;$('#currentTag').textContent=o.tag;$('#clientName').textContent=o.client;$('#clientPhone').textContent=o.phone;$('#deviceName').textContent=o.device;$('#deviceMeta').textContent=o.meta;$('#problemName').textContent=o.problem;$('#problemMeta').textContent=o.problemMeta;$('#amount').textContent=o.amount;$$('#stages .stage').forEach((s,n)=>s.classList.toggle('active',n===Math.min(o.stage-1,5)));$('#continueBtn').textContent=o.stage===6?'Открыть выдачу ›':`Продолжить шаг ${o.stage} ›`;setTimeout(()=>$('#currentOrder').scrollIntoView({behavior:'smooth',block:'start'}),120)}
$$('.order-card').forEach((c,i)=>c.addEventListener('click',()=>{selectOrder(i);toast(`Открыт заказ ${orders[i].id}`)}));$$('[data-order-open]').forEach(b=>b.addEventListener('click',()=>{showView('home');selectOrder(Number(b.dataset.orderOpen))}));

const suppliers=[
{name:'MobileParts Pro',note:'Оригинал снятый · состояние A',price:28900,eta:'Сегодня · 2 часа',stock:'2 шт.',score:1},
{name:'DeviceHub',note:'OEM Premium · гарантия 90 дней',price:21400,eta:'Завтра · 11:00',stock:'7 шт.',score:2},
{name:'FixComponent',note:'Совместимый OLED · гарантия 60 дней',price:16800,eta:'Сегодня · 4 часа',stock:'14 шт.',score:3}
];
function openTool(id){const el=document.getElementById(id);el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeTool(id){const el=document.getElementById(id);el.classList.remove('open');el.setAttribute('aria-hidden','true');document.body.style.overflow=''}
$('#photoSearchBtn').addEventListener('click',()=>openTool('photoSheet'));
$('#partsSearchBtn').addEventListener('click',()=>{renderSuppliers('balanced');openTool('partsSheet')});
$('#partsMoreBtn')?.addEventListener('click',()=>{renderSuppliers('balanced');openTool('partsSheet')});
$$('[data-close-tool]').forEach(btn=>btn.addEventListener('click',()=>closeTool(btn.dataset.closeTool)));
$$('.tool-sheet').forEach(layer=>layer.addEventListener('click',event=>{if(event.target===layer)closeTool(layer.id)}));
$('#cameraLaunch').addEventListener('click',()=>$('#devicePhotoInput').click());
let photoObjectUrl='';
$('#devicePhotoInput').addEventListener('change',event=>{const file=event.target.files?.[0];if(!file)return;if(photoObjectUrl)URL.revokeObjectURL(photoObjectUrl);photoObjectUrl=URL.createObjectURL(file);$('#photoPreview').innerHTML=`<img src="${photoObjectUrl}" alt="Локальный предпросмотр устройства">`;$('#visionResults').hidden=false;toast('Фото обработано локально в демонстрационном режиме')});
$$('.model-option').forEach(option=>option.addEventListener('click',()=>{$$('.model-option').forEach(item=>item.classList.remove('selected'));option.classList.add('selected');const title=option.querySelector('b').textContent;$('#confirmModel').textContent=`Подтвердить ${title}`}));
$('#confirmModel').addEventListener('click',()=>{const selected=$('.model-option.selected b')?.textContent||'устройство';closeTool('photoSheet');toast(`${selected} подтверждён сотрудником`)});
function renderSuppliers(sort){const list=[...suppliers];if(sort==='price')list.sort((a,b)=>a.price-b.price);if(sort==='speed')list.sort((a,b)=>a.score-b.score);if(sort==='balanced')list.sort((a,b)=>(a.price+a.score*1800)-(b.price+b.score*1800));$('#supplierList').innerHTML=list.map((s,index)=>`<article class="supplier-row ${index===0?'recommended':''}"><div class="supplier-name"><small>${index===0?'РЕКОМЕНДАЦИЯ AION':'ПОСТАВЩИК'}</small><b>${s.name}</b><span>${s.note} · ${s.stock}</span></div><div class="supplier-offer"><b>${s.price.toLocaleString('ru-RU')} ₽</b><span>${s.eta}</span></div><button class="supplier-action" data-supplier="${s.name}">${index===0?'Выбрать вариант':'Открыть предложение'}</button></article>`).join('');$$('[data-supplier]').forEach(btn=>btn.addEventListener('click',()=>toast(`${btn.dataset.supplier}: демо-выбор, резерв не создан`)))}
$$('.supplier-tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.supplier-tab').forEach(item=>item.classList.remove('active'));tab.classList.add('active');renderSuppliers(tab.dataset.sort)}));
$('#partQuery').addEventListener('input',()=>renderSuppliers($('.supplier-tab.active')?.dataset.sort||'balanced'));
renderSuppliers('balanced');

const sheet=$('#sheet'),host=$('#stepHost'),progress=$$('#intakeProgress i');let step=0;const steps=[
()=>`<div class="field"><label>Телефон клиента</label><input value="+7 900 123-45-67" inputmode="tel"></div><div class="suggestion"><small>ПОДГОТОВЛЕНО AION</small><b>Иван Петров</b><p>Найден существующий клиент. Проверьте совпадение перед подтверждением.</p></div>`,
()=>`<div class="field"><label>Устройство</label><select><option>iPhone 14 Pro · 256 GB · Deep Purple</option><option>Другая модель</option></select></div><div class="suggestion"><small>ПОДГОТОВЛЕНО AION</small><b>Последнее устройство клиента</b><p>Совпадение по истории — 92%. Устройство подтверждает сотрудник.</p></div>`,
()=>`<div class="field"><label>Проблема</label><select><option>Разбит экран / нет изображения</option><option>Не заряжается</option><option>Быстро разряжается</option></select></div><div class="field"><label>Комментарий</label><textarea>После падения отсутствует изображение.</textarea></div>`,
()=>`<div class="field"><label>Работа</label><input value="Замена дисплейного модуля"></div><div class="field"><label>Цена</label><input value="24 500 ₽"></div><div class="suggestion"><small>ПРЕДЛОЖЕНИЕ, НЕ ПОДТВЕРЖДЕНО</small><b>Гарантия 90 дней</b><p>Сотрудник подтверждает итоговые условия.</p></div>`,
()=>`<div class="field"><label>Согласие клиента</label><textarea readonly>Клиент подтверждает устройство, состояние, работы, цену и гарантию. DEMO-CONSENT-v1.</textarea></div><div class="field"><label>Подпись</label><input value="Иван Петров"></div>`,
()=>`<div class="receipt"><div class="ok">✓</div><h3>Демонстрационный заказ создан</h3><p>Сервер, защищённый QR и юридическое хранение подписи пока не подключены.</p></div>`];
function renderStep(){host.innerHTML=steps[step]();progress.forEach((p,i)=>p.classList.toggle('done',i<=step));$('#backStep').disabled=step===0;$('#nextStep').textContent=step===5?'Закрыть':'Подтвердить и продолжить'}function openSheet(){step=0;renderStep();sheet.classList.add('open');sheet.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeSheet(){sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true');document.body.style.overflow=''}$$('.open-intake').forEach(b=>b.addEventListener('click',openSheet));$('#closeSheet').addEventListener('click',closeSheet);sheet.addEventListener('click',e=>{if(e.target===sheet)closeSheet()});$('#backStep').addEventListener('click',()=>{if(step>0){step--;renderStep()}});$('#nextStep').addEventListener('click',()=>{if(step<5){step++;renderStep()}else{closeSheet();toast('Демо-сценарий завершён')}});renderStep();