const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const store={get(k,f){try{return localStorage.getItem(k)||f}catch{return f}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
const orders=[
{id:'#A-10234',tag:'В работе',client:'Иван Петров',phone:'+7 900 123-45-67',device:'iPhone 14 Pro',meta:'256 GB, Deep Purple',problem:'Разбит экран',problemMeta:'Нет изображения',amount:'24 500 ₽',stage:1},
{id:'#A-10233',tag:'Диагностика',client:'Анна Кузнецова',phone:'+7 912 444-09-12',device:'Samsung S23',meta:'128 GB, Phantom Black',problem:'Не заряжается',problemMeta:'Проверка разъёма и АКБ',amount:'3 500 ₽',stage:2},
{id:'#A-10232',tag:'К выдаче',client:'Сергей Дмитриев',phone:'+7 922 018-22-44',device:'iPhone 11',meta:'128 GB, Black',problem:'Замена аккумулятора',problemMeta:'ОТК пройден',amount:'6 490 ₽',stage:6}
];
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),1700)}
function updateClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}updateClock();setInterval(updateClock,30000);
function setTheme(theme){document.documentElement.dataset.theme=theme;store.set('aion.comfort.v6.theme',theme);document.querySelector('meta[name="theme-color"]').setAttribute('content',theme==='light'?'#eef3fb':'#030713');$('#themeIcon').innerHTML=theme==='light'?'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.66 6.34l1.41-1.41"/>':'<path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z"/>'}
setTheme(store.get('aion.comfort.v6.theme','dark'));
$('#themeBtn').addEventListener('click',()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';setTheme(t);toast(t==='light'?'Светлая тема включена':'Тёмная тема включена')});
const viewNames={home:'Главная',orders:'Заказы',clients:'Клиенты',more:'Ещё'};
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('.nav[data-view-target]').forEach(n=>n.classList.toggle('active',n.dataset.viewTarget===name));$('#viewTitle').textContent=viewNames[name]||'AION';window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});store.set('aion.comfort.v6.view',name)}
$$('[data-view-target]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewTarget)));showView(store.get('aion.comfort.v6.view','home'));
$$('[data-toast]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.toast)));
$('#quickBtn').addEventListener('click',()=>toast('Быстрый доступ: новый ремонт, поиск и выдача'));
$('#bellBtn').addEventListener('click',()=>toast('3 уведомления: выдача, оплата и просроченная задача'));
$('#profileBtn').addEventListener('click',()=>toast('Профиль Максима — демонстрационный режим'));
$('#eveBtn').addEventListener('click',()=>{toast('EvE открывает приоритетный заказ');showView('home');setTimeout(()=>document.querySelector('[data-order="2"]').click(),100)});
function selectOrder(i){const o=orders[i];$$('.order-card').forEach((c,n)=>c.classList.toggle('active',n===i));$('#currentId').textContent=o.id;$('#currentTag').textContent=o.tag;$('#clientName').textContent=o.client;$('#clientPhone').textContent=o.phone;$('#deviceName').textContent=o.device;$('#deviceMeta').textContent=o.meta;$('#problemName').textContent=o.problem;$('#problemMeta').textContent=o.problemMeta;$('#amount').textContent=o.amount;$$('#stages .stage').forEach((s,n)=>s.classList.toggle('active',n===Math.min(o.stage-1,5)));$('#continueBtn').textContent=o.stage===6?'Открыть выдачу ›':`Продолжить шаг ${o.stage} ›`;setTimeout(()=>$('#currentOrder').scrollIntoView({behavior:'smooth',block:'start'}),120)}
$$('.order-card').forEach((c,i)=>c.addEventListener('click',()=>{selectOrder(i);toast(`Открыт заказ ${orders[i].id}`)}));$$('[data-order-open]').forEach(b=>b.addEventListener('click',()=>{showView('home');selectOrder(Number(b.dataset.orderOpen))}));
const moduleCatalog={
 qr:{name:'QR устройства',note:'Найти заказ или клиента',badge:'Камера',icon:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><path d="M14 14h3v3h-3zM19 14h2v2M18 19h3v2M14 19h2v2"/></svg>',action:'qr'},
 photo:{name:'Поиск по фото',note:'Похожие модели с подтверждением',badge:'Локально',icon:'<svg viewBox="0 0 24 24"><path d="M4 7h3l1.5-2h7L17 7h3v12H4Z"/><circle cx="12" cy="13" r="4"/></svg>',action:'photo'},
 parts:{name:'Запчасти',note:'Цена, наличие и срок',badge:'3 варианта',icon:'<svg viewBox="0 0 24 24"><path d="M4 7l8-4 8 4-8 4-8-4Z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/></svg>',action:'parts'},
 stock:{name:'Склад',note:'Резерв и остатки',badge:'36',icon:'<svg viewBox="0 0 24 24"><path d="M4 7l8-4 8 4-8 4-8-4Z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/></svg>',action:'stock'},
 reports:{name:'Отчёты',note:'Деньги, сроки, эффективность',badge:'Сегодня',icon:'<svg viewBox="0 0 24 24"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>',action:'reports'},
 qc:{name:'ОТК',note:'Проверка перед выдачей',badge:'2 готовы',icon:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/><circle cx="12" cy="12" r="10"/></svg>',action:'qc'}
};
const defaultLayout=[
{id:'qr',tab:'home',visible:true},{id:'photo',tab:'home',visible:true},{id:'parts',tab:'home',visible:true},
{id:'qc',tab:'clients',visible:true},{id:'stock',tab:'more',visible:true},{id:'reports',tab:'more',visible:true}
];
function loadLayout(){try{const raw=JSON.parse(store.get('aion.comfort.v6.modules','null'));if(Array.isArray(raw)&&raw.length)return raw}catch{}return structuredClone(defaultLayout)}
let moduleLayout=loadLayout();
function saveLayout(){store.set('aion.comfort.v6.modules',JSON.stringify(moduleLayout))}
function moduleMarkup(item){const m=moduleCatalog[item.id];return `<button class="movable-module" data-module-action="${m.action}"><span class="module-glyph">${m.icon}</span><span class="module-badge">${m.badge}</span><b>${m.name}</b><small>${m.note}</small></button>`}
function renderModules(){for(const tab of ['home','clients','more']){const host=document.getElementById(tab==='clients'?'clientModules':`${tab}Modules`);host.innerHTML=moduleLayout.filter(x=>x.visible&&x.tab===tab).map(moduleMarkup).join('')||'<div class="empty-state">Нет закреплённых модулей</div>'}bindModuleActions();renderManager()}
function bindModuleActions(){$$('[data-module-action]').forEach(btn=>btn.addEventListener('click',()=>runModule(btn.dataset.moduleAction)))}
function runModule(action){if(action==='qr')openTool('qrSheet');else if(action==='photo')openTool('photoSheet');else if(action==='parts'){renderSuppliers('balanced');openTool('partsSheet')}else if(action==='stock')toast('Склад: продуктовый модуль ещё не подключён');else if(action==='reports')toast('Отчёты: демонстрационная точка входа');else if(action==='qc')toast('ОТК: 2 заказа готовы к проверке')}
function renderManager(){const host=$('#moduleManager');host.innerHTML=moduleLayout.map(item=>{const m=moduleCatalog[item.id];return `<div class="module-manager-row"><span class="manager-name"><b>${m.name}</b><small>${m.note}</small></span><select data-module-tab="${item.id}"><option value="home" ${item.tab==='home'?'selected':''}>Главная</option><option value="clients" ${item.tab==='clients'?'selected':''}>Клиенты</option><option value="more" ${item.tab==='more'?'selected':''}>Ещё</option></select><button data-move="up" data-id="${item.id}" aria-label="Поднять">↑</button><button data-move="down" data-id="${item.id}" aria-label="Опустить">↓</button><label title="Показать модуль"><input type="checkbox" data-visible="${item.id}" ${item.visible?'checked':''}></label></div>`}).join('');
 $$('[data-module-tab]').forEach(select=>select.addEventListener('change',()=>{const item=moduleLayout.find(x=>x.id===select.dataset.moduleTab);item.tab=select.value;saveLayout();renderModules()}));
 $$('[data-visible]').forEach(input=>input.addEventListener('change',()=>{moduleLayout.find(x=>x.id===input.dataset.visible).visible=input.checked;saveLayout();renderModules()}));
 $$('[data-move]').forEach(btn=>btn.addEventListener('click',()=>{const index=moduleLayout.findIndex(x=>x.id===btn.dataset.id);const delta=btn.dataset.move==='up'?-1:1;const target=index+delta;if(target<0||target>=moduleLayout.length)return;[moduleLayout[index],moduleLayout[target]]=[moduleLayout[target],moduleLayout[index]];saveLayout();renderModules()}));
}
$('#resetLayoutBtn').addEventListener('click',()=>{moduleLayout=structuredClone(defaultLayout);saveLayout();renderModules();toast('Рабочее пространство восстановлено')});
renderModules();
const suppliers=[
{name:'MobileParts Pro',note:'Оригинал снятый · состояние A',price:28900,eta:'Сегодня · 2 часа',stock:'2 шт.',score:1},
{name:'DeviceHub',note:'OEM Premium · гарантия 90 дней',price:21400,eta:'Завтра · 11:00',stock:'7 шт.',score:2},
{name:'FixComponent',note:'Совместимый OLED · гарантия 60 дней',price:16800,eta:'Сегодня · 4 часа',stock:'14 шт.',score:3}
];
function openTool(id){const el=document.getElementById(id);el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeTool(id){const el=document.getElementById(id);el.classList.remove('open');el.setAttribute('aria-hidden','true');document.body.style.overflow=''}
$('#clientQrBtn').addEventListener('click',()=>openTool('qrSheet'));
$$('[data-close-tool]').forEach(btn=>btn.addEventListener('click',()=>closeTool(btn.dataset.closeTool)));
$$('.tool-sheet').forEach(layer=>layer.addEventListener('click',event=>{if(event.target===layer)closeTool(layer.id)}));
let qrObjectUrl='';$('#qrCameraLaunch').addEventListener('click',()=>$('#qrPhotoInput').click());
$('#qrPhotoInput').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;if(qrObjectUrl)URL.revokeObjectURL(qrObjectUrl);qrObjectUrl=URL.createObjectURL(file);$('#qrPreview').innerHTML=`<img src="${qrObjectUrl}" alt="Локальный предпросмотр QR">`;let detected=false;try{if('BarcodeDetector' in window){const detector=new BarcodeDetector({formats:['qr_code']});const bitmap=await createImageBitmap(file);const codes=await detector.detect(bitmap);detected=codes.length>0}}catch{}$('#qrResult').hidden=false;toast(detected?'QR найден локально':'Показан демонстрационный результат: реальный декодер не подтверждён')});
$('#openQrOrder').addEventListener('click',()=>{closeTool('qrSheet');showView('home');selectOrder(2);toast('Открыт демонстрационный заказ #A-10232')});
$('#cameraLaunch').addEventListener('click',()=>$('#devicePhotoInput').click());let photoObjectUrl='';
$('#devicePhotoInput').addEventListener('change',event=>{const file=event.target.files?.[0];if(!file)return;if(photoObjectUrl)URL.revokeObjectURL(photoObjectUrl);photoObjectUrl=URL.createObjectURL(file);$('#photoPreview').innerHTML=`<img src="${photoObjectUrl}" alt="Локальный предпросмотр устройства">`;$('#visionResults').hidden=false;toast('Фото обработано локально в демонстрационном режиме')});
$$('.model-option').forEach(option=>option.addEventListener('click',()=>{$$('.model-option').forEach(item=>item.classList.remove('selected'));option.classList.add('selected');const title=option.querySelector('b').textContent;$('#confirmModel').textContent=`Подтвердить ${title}`}));
$('#confirmModel').addEventListener('click',()=>{const selected=$('.model-option.selected b')?.textContent||'устройство';closeTool('photoSheet');toast(`${selected} подтверждён сотрудником`)});
function renderSuppliers(sort){const list=[...suppliers];if(sort==='price')list.sort((a,b)=>a.price-b.price);if(sort==='speed')list.sort((a,b)=>a.score-b.score);if(sort==='balanced')list.sort((a,b)=>(a.price+a.score*1800)-(b.price+b.score*1800));$('#supplierList').innerHTML=list.map((s,index)=>`<article class="supplier-row ${index===0?'recommended':''}"><div class="supplier-name"><small>${index===0?'РЕКОМЕНДАЦИЯ AION':'ПОСТАВЩИК'}</small><b>${s.name}</b><span>${s.note} · ${s.stock}</span></div><div class="supplier-offer"><b>${s.price.toLocaleString('ru-RU')} ₽</b><span>${s.eta}</span></div><button class="supplier-action" data-supplier="${s.name}">${index===0?'Выбрать вариант':'Открыть предложение'}</button></article>`).join('');$$('[data-supplier]').forEach(btn=>btn.addEventListener('click',()=>toast(`${btn.dataset.supplier}: демо-выбор, резерв не создан`)))}
$$('.supplier-tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.supplier-tab').forEach(item=>item.classList.remove('active'));tab.classList.add('active');renderSuppliers(tab.dataset.sort)}));$('#partQuery').addEventListener('input',()=>renderSuppliers($('.supplier-tab.active')?.dataset.sort||'balanced'));renderSuppliers('balanced');
const sheet=$('#sheet'),host=$('#stepHost'),progress=$$('#intakeProgress i');let step=0;const steps=[
()=>`<div class="field"><label>Телефон клиента</label><input value="+7 900 123-45-67" inputmode="tel"></div><div class="suggestion"><small>ПОДГОТОВЛЕНО AION</small><b>Иван Петров</b><p>Найден существующий клиент. Проверьте совпадение перед подтверждением.</p></div>`,
()=>`<div class="field"><label>Устройство</label><select><option>iPhone 14 Pro · 256 GB · Deep Purple</option><option>Другая модель</option></select></div><div class="suggestion"><small>ПОДГОТОВЛЕНО AION</small><b>Последнее устройство клиента</b><p>Совпадение по истории — 92%. Устройство подтверждает сотрудник.</p></div>`,
()=>`<div class="field"><label>Проблема</label><select><option>Разбит экран / нет изображения</option><option>Не заряжается</option><option>Быстро разряжается</option></select></div><div class="field"><label>Комментарий</label><textarea>После падения отсутствует изображение.</textarea></div>`,
()=>`<div class="field"><label>Работа</label><input value="Замена дисплейного модуля"></div><div class="field"><label>Цена</label><input value="24 500 ₽"></div><div class="suggestion"><small>ПРЕДЛОЖЕНИЕ, НЕ ПОДТВЕРЖДЕНО</small><b>Гарантия 90 дней</b><p>Сотрудник подтверждает итоговые условия.</p></div>`,
()=>`<div class="field"><label>Согласие клиента</label><textarea readonly>Клиент подтверждает устройство, состояние, работы, цену и гарантию. DEMO-CONSENT-v1.</textarea></div><div class="field"><label>Подпись</label><input value="Иван Петров"></div>`,
()=>`<div class="receipt"><div class="ok">✓</div><h3>Демонстрационный заказ создан</h3><p>Сервер, защищённый QR и юридическое хранение подписи пока не подключены.</p></div>`];
function renderStep(){host.innerHTML=steps[step]();progress.forEach((p,i)=>p.classList.toggle('done',i<=step));$('#backStep').disabled=step===0;$('#nextStep').textContent=step===5?'Закрыть':'Подтвердить и продолжить'}function openSheet(){step=0;renderStep();sheet.classList.add('open');sheet.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeSheet(){sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true');document.body.style.overflow=''}$$('.open-intake').forEach(b=>b.addEventListener('click',openSheet));$('#closeSheet').addEventListener('click',closeSheet);sheet.addEventListener('click',e=>{if(e.target===sheet)closeSheet()});$('#backStep').addEventListener('click',()=>{if(step>0){step--;renderStep()}});$('#nextStep').addEventListener('click',()=>{if(step<5){step++;renderStep()}else{closeSheet();toast('Демо-сценарий завершён')}});renderStep();
