(()=>{setTimeout(()=>{
state.v07=Object.assign({orderPhase:'repair_done',paymentPending:false,scaleLevel:0},state.v07||{});
const SM={[-2]:.9,[-1]:.95,0:1,1:1.1,2:1.2,3:1.3,4:1.4,5:1.5};
const scale=(l)=>{l=Math.max(-2,Math.min(5,+l||0));let m=SM[l];state.v07.scaleLevel=l;let r=document.documentElement;r.style.setProperty('--ui-scale',m);r.style.setProperty('--text-scale',m);r.style.setProperty('--icon-scale',m);r.style.setProperty('--control-scale',m);r.style.setProperty('--space-scale',Math.min(m,1.35));r.style.setProperty('--radius-scale',Math.min(m,1.28));app.dataset.scaleLevel=l;let v=q('#scaleValue');if(v)v.textContent=Math.round(m*100)+'%';try{localStorage.setItem('aion-v07-ui-scale',l)}catch(_){} };
try{state.v07.scaleLevel=+localStorage.getItem('aion-v07-ui-scale')||0}catch(_){}
let top=q('.topbar'),cl=q('.navCluster');if(!cl){cl=document.createElement('div');cl.className='navCluster';top.insertBefore(cl,leftBtn);cl.appendChild(leftBtn);let h=document.createElement('button');h.className='headBtn homeHeadBtn';h.id='homeHeadBtn';h.innerHTML=ico('i-home');h.ariaLabel='На Главную';cl.appendChild(h);h.onclick=e=>{e.stopPropagation();closeLayers();nav=[];navigate('home',{},true)}}
leftBtn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();closeLayers();current==='home'?(drawer.classList.toggle('open'),syncShade(),renderDrawer()):goBack()},true);
const oldST=screenTitle;screenTitle=s=>s==='home'?(lang==='ru'?'Главная':'Home'):oldST(s);
updateShell=()=>{title.textContent=screenTitle(current);app.classList.toggle('home-screen',current==='home');app.classList.toggle('nested-screen',current!=='home');leftBtn.innerHTML=current==='home'?'<span class="hamb"><i></i><i></i><i></i></span>':ico('i-back','lg');let p=q('#photoLabel'),s=q('#searchLabel');if(p)p.textContent=T('photo');if(s)s.textContent=T('search');renderDrawer()};
let sb=q('.settingsBox');if(sb)sb.innerHTML=`<button class="ctrl" data-act="v7-sm">A−</button><button class="ctrl scaleReadout" id="scaleValue" data-act="v7-s0">100%</button><button class="ctrl" data-act="v7-sp">A+</button><button class="ctrl" data-act="language">RU</button><button class="ctrl" data-act="theme"><span class="orb"></span></button><button class="ctrl" data-act="login">${ico('i-user','sm')}</button><button class="ctrl" data-act="v7-home">${ico('i-home','sm')}</button>`;
const ws=(ic,t,sub,now,req,next)=>`<section class="contextWorkspace"><div class="workspaceIdentity"><span class="iconWell">${ico(ic)}</span><div><h2>${t}</h2><p>${sub}</p></div></div><div class="workspaceTruth"><div class="workspaceTruthLine"><label>СЕЙЧАС</label><b>${now}</b></div><div class="workspaceTruthLine"><label>ТРЕБУЕТ</label><b>${req}</b></div><div class="workspaceTruthLine"><label>СЛЕДУЮЩЕЕ</label><b>${next}</b></div></div></section>`;
const df=(k,l,ic)=>{let v=state.context[k];return `<div class="draftFact ${v?'known':'missing'}" data-act="context:${k}">${ico(v?'i-check':ic)}<label>${l}</label><b>${v?esc(v):'Не заполнено'}</b></div>`};
const proof=(t,rows)=>openModal(`${hero(t,'Proof Chain прототипа.')}<div class="proofList">${rows.map(x=>`<div class="proofRow"><label>${x[0]}</label><b>${x[1]}</b></div>`).join('')}</div>${btn('Закрыть','modal-close','','primary')}`);
screens.home=()=>`<div class="liveHome"><div class="liveHello"><b>AION Service</b><span>Добрый день, Иван</span></div><section class="attentionCard"><div class="attentionHead"><b>Требует внимания</b><small>по действию</small></div>${[['i-clipboard','№000125','Диагностика завершена · Нужно согласование','overdue','Просрочено','09:10','approval'],['i-box','№000128','Деталь прибыла · Продолжить ремонт','block','Деталь','10:25','order_part'],['i-shield','№000124','Ремонт завершён · Нужен QC','qc','QC','11:40','qc'],['i-money','№000123','QC пройден · Осталось 2 500 ₽','pay','Оплата','12:15','payment'],['i-check','№000122','Все условия выполнены · Готов к выдаче','ready','Готов','14:05','issue']].map(x=>`<button class="attentionRow" data-go="${x[6]}"><span class="attentionIcon">${ico(x[0])}</span><span class="attentionText"><b>Заказ ${x[1]}</b><small>${x[2]}</small></span><span class="attentionBadge ${x[3]}">${x[4]}</span><time>${x[5]}</time></button>`).join('')}<button class="liveAll" data-go="tasks">Всё внимание →</button></section><div class="liveActions"><button class="liveAction primary" data-act="new-empty"><span class="liveActionIcon">${ico('i-plus')}</span><span class="liveActionText"><b>Новый ремонт</b><small>Начать откуда угодно</small></span></button><button class="liveAction" data-go="capture"><span class="liveActionIcon">${ico('i-search')}</span><span class="liveActionText"><b>Найти что угодно</b><small>Фото · QR · Поиск · Голос</small></span></button></div><div class="homeShortcutsZone" id="freeZone" data-empty="${state.pinned.length?'false':'true'}"><div class="shortcuts" id="shortcuts"></div></div><aside class="aionNotice"><div class="aionNoticeHead">AION заметил</div><p>Заказ №000125 ждёт согласование дольше обычного. Рекомендация: позвонить клиенту.</p><button class="textLink" data-act="v7-why">Почему?</button></aside></div>`;
screens.tasks=()=>`${hero('Требует внимания','Задачи и уведомления объединены. Нажатие ведёт сразу к нужному действию.')}${row('i-clipboard','Просрочено · №000125','Нужно согласование','approval')}${row('i-box','Деталь прибыла · №000128','Продолжить ремонт','order_part')}${row('i-shield','Нужен QC · №000124','Провести проверку','qc')}${row('i-money','Нужна оплата · №000123','Осталось 2 500 ₽','payment')}${row('i-check','Готов к выдаче · №000122','Все условия выполнены','issue')}`;
screens.capture=()=>`${hero('Дайте AION любой контекст','Имя, телефон, устройство, IMEI/SN, заказ, QR, фото, услуга, деталь, поставщик или голос.')}<section class="captureSurface"><div class="captureTypes">${['Клиент','Телефон','Устройство','IMEI/SN','Заказ','QR','Фото','Услуга','Деталь','Поставщик','Голос'].map(x=>`<span class="captureType">${x}</span>`).join('')}</div>${searchBox('Найти что угодно…','globalCapture')}<div class="captureButtons">${btn(`${ico('i-camera','sm')} Фото / QR`,'v7-scan','','primary')}${btn(`${ico('i-mic','sm')} Голос`,'voice')}</div></section><div class="note">Сначала возможное совпадение, затем подтверждение.</div>`;
screens.search=()=>`${hero('Найти что угодно','Один поиск по всей поверхности продукта.')}${searchBox('Иванов, iPhone 13, IMEI, №125…','globalSearch')}<div class="bigMic" id="micBtn" data-act="voice">${ico('i-mic','xl')}</div>${btn('Найти','do-search','','primary')}`;
screens.recognition=()=>`${hero('Возможное совпадение','AION собрал контекст. Подтвердите перед продолжением.')}${section('Распознано',info('Клиент','Иван Иван')+info('Устройство','iPhone 13')+info('IMEI','356789012345678')+info('Деталь','Дисплей iPhone 13'))}${btn('Продолжить с этим контекстом','v7-rec','','primary')}<button class="textLink" data-go="verify">Исправить вручную</button>`;
screens.search_results=()=>`${hero('Результаты','Откройте объект или начните ремонт с найденным контекстом.')}${row('i-user','Иван Иван','+7 (900) 123-45-67','client')}${row('i-phone','iPhone 13','IMEI 356…','device')}${row('i-clipboard','Заказ №000125','Ремонт завершён · Нужен QC','order')}${btn('Новый ремонт с найденным контекстом','search-new','','primary')}`;
screens.client=()=>`${ws('i-user','Иван Иван','+7 (900) 123-45-67','iPhone 13 · ремонт №125','Согласование','Позвонить клиенту')}${btn('Новый ремонт','new-client-repair','','primary')}<div class="tabs"><button class="tab" data-go="devices">Устройства</button><button class="tab" data-go="client_history">История</button><button class="tab" data-go="client_docs">Документы</button></div>`;
screens.device=()=>`${ws('i-phone','iPhone 13','IMEI 356789012345678','Ремонт №125 · работа завершена','Независимый QC','Передать на QC')}${btn('Новый ремонт','new-device-repair','','primary')}${section('Связанные данные',row('i-history','История ремонтов','3 заказа','repair_history')+row('i-shield','Гарантия','До 12.05.2027','warranty')+row('i-clipboard','Текущий заказ','№000125','order'))}`;
screens.service=()=>`${ws('i-tag',state.context.service||'Замена дисплея','iPhone 13 · 5 000 ₽','Доступна для iPhone 13','Выбрать клиента / устройство','Начать ремонт')}${section('Параметры',info('Цена','5 000 ₽')+info('Время','60 мин'))}${btn('Новый ремонт с этой услугой','service-new','','primary')}`;
screens.part=()=>`${ws('i-box',state.context.part||'Дисплей iPhone 13','Остаток 12 шт · 3 200 ₽','Деталь в наличии','Выбрать ремонт','Начать ремонт')}${section('Параметры',info('Остаток','12 шт')+info('Цена','3 200 ₽'))}${btn('Новый ремонт с этой деталью','part-new','','primary')}`;
screens.suppliers=()=>`${searchBox('Поиск поставщиков','supplierSearch')}${suppliers.map((x,i)=>row('i-cart',x[0],`${x[2]} · ${x[3]}`,'',x[1],`v7-supplier:${i}`)).join('')}`;
screens.client_history=()=>`${row('i-history','№00012345','12.05.2026 · iPhone 13','order')}${row('i-history','№00011987','28.02.2026 · Samsung S21','order')}${btn('Новый ремонт из истории','new-client-repair','','primary')}`;
screens.documents=()=>`${row('i-doc','Квитанция','Заказ №000125','receipt')}${row('i-doc','Акт работ','Заказ №000125','act')}${row('i-shield','Гарантийный талон','До 12.05.2027','warranty_doc')}${row('i-qr','QR-статус','№000125','qr_status')}${btn('Новый ремонт из контекста заказа','v7-docnew','','primary')}`;
screens.draft=()=>{let ok=['client','device','service'].every(k=>state.context[k]);return `<div class="livingDraft">${hero('Новый ремонт','Заполняйте в любом порядке. Известный контекст сохраняется.')}<div class="draftFacts">${df('client','Клиент','i-user')}${df('device','Устройство','i-phone')}${df('service','Услуга','i-tag')}${df('part','Деталь','i-box')}${df('supplier','Поставщик','i-cart')}${df('comment','Комментарий','i-edit')}</div><div class="draftContract">${ok?'Минимальный business contract выполнен.':'Нужно: клиент, устройство и услуга.'}</div><button class="btn primary" data-act="v7-create" ${ok?'':'disabled'}>Создать ремонт</button><div><button class="textLink" data-go="capture">Фото / QR</button> · <button class="textLink" data-go="search">Поиск / Голос</button></div></div>`};
screens.diagnostics=()=>`${hero('Диагностика','Факты сохраняются в контексте ремонта.')}${section('Проверка',state.diagnostics.map((v,i)=>`<div class="checkLine" data-act="diag:${i}"><span class="checkbox ${v?'on':''}">${v?ico('i-check','sm'):''}</span><span>Диагностическая запись ${i+1}</span></div>`).join(''))}${btn('К стоимости','', 'cost','primary')}`;
screens.cost=()=>`${section('Стоимость',`<div class="listLine"><span class="grow">Замена дисплея</span><b>1 500 ₽</b></div><div class="listLine"><span class="grow">Дисплей iPhone 13</span><b>2 000 ₽</b></div><div class="listLine"><b class="grow">Итого</b><b>3 500 ₽</b></div>`)}${btn('Согласовать с клиентом','', 'approval','primary')}`;
screens.approval=()=>`${ws('i-user','Иван Иван','iPhone 13 · ремонт №125','Диагностика завершена','Согласование 3 500 ₽','Согласовать')}<textarea class="textarea" placeholder="Комментарий клиента"></textarea>${btn('Согласовать','v7-approve','','primary')}<button class="textLink" data-act="decline">Клиент отказался</button>`;
screens.signature=()=>`${hero('Подтверждение','Подпись подтверждает согласование работ.')}<div class="signature" id="sig"><canvas id="sigCanvas"></canvas><div class="sigHint" id="sigHint">Подписать пальцем</div></div>${btn('Подтвердить согласование','v7-sign','','primary')}`;
screens.work=()=>`${hero('Работа','Одна основная операция — завершить подтверждённую работу.')}<textarea class="textarea">Замена дисплейного модуля.</textarea>${btn('Завершить работу','v7-work','','primary')}`;
const OD=()=>state.paymentOk?['QC пройден · Оплата подтверждена','Выдача клиенту','Нет блокировок','Выдать клиенту','v7-issuego','Выдать клиенту']:state.qcPassed?['Ремонт завершён · QC пройден','Оплата 2 500 ₽','Выдача недоступна до оплаты','Принять 2 500 ₽','v7-paygo','Принять 2 500 ₽']:['Ремонт завершён','Независимый QC','Выдача недоступна','Передать на QC','v7-qcgo','Передать на QC'];
screens.order=()=>{let d=OD();return `<div class="truthView"><div class="truthIdentity"><h2>Заказ №000125</h2><p>iPhone 13 · Иван Иван</p></div><section class="truthStack"><div class="truthBlock confirmed"><label>✓ ПОДТВЕРЖДЕНО</label><b>${d[0]}</b><small>17:42 · Петров</small></div><div class="truthBlock requires"><label>⚠ ТРЕБУЕТ</label><b>${d[1]}</b></div><div class="truthBlock blocker"><label>🔒 БЛОКИРУЕТ</label><b>${d[2]}</b></div><div class="truthBlock next"><label>→ СЛЕДУЮЩЕЕ</label><b>${d[3]}</b></div></section>${btn(d[5],d[4],'','primary')}<button class="textLink" data-act="v7-proof">Почему?</button><button class="textLink" data-act="v7-ordernew">Новый ремонт из этого заказа</button></div>`};
screens.qc=()=>`${hero('QC / Проверка','Независимая проверка перед оплатой и выдачей.')}${section('Чек-лист',['Экран','Сенсор','Связь','Камеры','Динамики','Зарядка','Внешний вид','Комплектность'].map((x,i)=>`<div class="checkLine" data-act="qc-check:${i}"><span class="checkbox ${state.checks[i]?'on':''}">${state.checks[i]?ico('i-check','sm'):''}</span><span>${x}</span></div>`).join(''))}${btn('QC пройден','v7-qcpass','','primary')}<button class="textLink" data-act="v7-qcfail">Есть проблема → вернуть в ремонт</button>`;
screens.payment=()=>state.v07.paymentPending?`${hero('Оплата','Не повторяем операцию вслепую.')}<div class="pendingState"><span class="pendingDot"></span><b>Проверяем результат оплаты…</b></div>`:state.paymentOk?`${hero('Оплата','Authoritative reread подтверждён.')}<section class="paymentSummary"><div class="moneyLine"><span>Итого</span><b>12 500 ₽</b></div><div class="moneyLine"><span>Оплачено</span><b>12 500 ₽</b></div><div class="moneyLine"><span>Осталось</span><b>0 ₽</b></div></section>${btn('К выдаче','v7-issuego','','primary')}`:`${hero('Оплата','Суммы из финансового источника.')}<section class="paymentSummary"><div class="moneyLine"><span>Итого</span><b>12 500 ₽</b></div><div class="moneyLine"><span>Оплачено</span><b>10 000 ₽</b></div><div class="moneyLine"><span>Осталось</span><b>2 500 ₽</b></div></section>${btn('Принять 2 500 ₽','v7-pay','','primary')}`;
screens.issue=()=>{let ok=(!state.qcMandatory||state.qcPassed)&&(state.paymentOk||state.debtAllowed);return ok?`${hero('Выдача','Все условия подтверждены.')}${section('Факты',`<div class="factCheck">✓ Ремонт завершён</div><div class="factCheck">✓ QC пройден</div><div class="factCheck">✓ Оплата подтверждена</div>`)}${btn('Выдать клиенту','v7-issue','','primary')}`:`${hero('ВЫДАЧА ЗАБЛОКИРОВАНА','Показываем причину, а не техническую ошибку.')}${section('Факты',`<div class="factCheck">${state.qcPassed?'✓':'✕'} QC</div><div class="factCheck">${state.paymentOk?'✓':'✕'} Осталось оплатить 2 500 ₽</div>`)}${btn(state.qcPassed?'Принять оплату':'Перейти к QC',state.qcPassed?'v7-paygo':'v7-qcgo','','primary')}<button class="textLink" data-act="v7-proof">Почему?</button>`};
const bh=handleAction;handleAction=(a,e)=>{if(a==='v7-sm')return scale(state.v07.scaleLevel-1);if(a==='v7-sp')return scale(state.v07.scaleLevel+1);if(a==='v7-s0')return scale(0);if(a==='v7-home'){closeLayers();nav=[];return navigate('home',{},true)}if(a==='v7-why')return proof('Почему AION рекомендует звонок?',[['Факт','Диагностика завершена'],['Ожидание','3ч 12м'],['Источник','Время этапа заказа']]);if(a==='v7-scan'){toastMsg('AION анализирует вход…');return setTimeout(()=>navigate('recognition'),400)}if(a==='v7-rec'){resetContext({client:'Иван Иван',device:'iPhone 13',part:'Дисплей iPhone 13'});return navigate('draft')}if(a.startsWith('v7-supplier:')){let i=+a.split(':')[1];resetContext({supplier:suppliers[i][0]});return navigate('draft')}if(a==='v7-docnew'){resetContext({client:'Иван Иван',device:'iPhone 13'});return navigate('draft')}if(a==='v7-ordernew'){resetContext({client:'Иван Иван',device:'iPhone 13'});return navigate('draft')}if(a==='v7-create')return navigate('diagnostics');if(a==='v7-approve')return navigate('signature');if(a==='v7-sign')return navigate('work');if(a==='v7-work'){state.qcPassed=false;state.paymentOk=false;return navigate('order')}if(a==='v7-qcgo')return navigate('qc');if(a==='v7-qcpass'){if(state.qcMandatory&&Object.keys(state.checks).filter(k=>state.checks[k]).length<8)return toastMsg('Отметьте все пункты QC');state.qcPassed=true;return navigate('order')}if(a==='v7-qcfail'){state.qcPassed=false;toastMsg('QC FAILED → возврат в ремонт');return navigate('work')}if(a==='v7-paygo')return navigate('payment');if(a==='v7-pay'){if(state.qcMandatory&&!state.qcPassed)return toastMsg('Сначала QC');state.v07.paymentPending=true;rerender();return setTimeout(()=>{state.v07.paymentPending=false;state.paymentOk=true;rerender();toastMsg('✓ Оплата подтверждена')},900)}if(a==='v7-issuego')return navigate('issue');if(a==='v7-issue'){toastMsg('✓ Выдача подтверждена');return setTimeout(()=>navigate('documents'),400)}if(a==='v7-proof')return proof('Proof Chain',[['Ремонт','Завершён · Петров · 17:42'],['QC',state.qcPassed?'Пройден':'Не пройден'],['Оплата',state.paymentOk?'Подтверждена':'Остаток 2 500 ₽'],['Правило','QC + оплата до выдачи']]);return bh(a,e)};
let ed=null;app.addEventListener('touchstart',e=>{let p=e.touches[0];if(p.clientX<24)ed={x:p.clientX,y:p.clientY}},{passive:true});app.addEventListener('touchend',e=>{if(!ed)return;let p=e.changedTouches[0];if(p.clientX-ed.x>52&&Math.abs(p.clientY-ed.y)<70&&current!=='home')goBack();ed=null},{passive:true});
window.__AION_V07__={goto:s=>{nav=[];navigate(s,{},true)},scale};
scale(state.v07.scaleLevel);nav=[];navigate('home',{},true);setTimeout(updateShell,50)
},30)})()