const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const storage={get:(k,d)=>{try{return localStorage.getItem(k)??d}catch(e){return d}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch(e){}}};
const app=$('#app'),header=$('.header'),stage=$('#stage'),headLeft=$('#headLeft'),headerTitle=$('#headerTitle'),gearBtn=$('#gearBtn'),settingsBar=$('#settingsBar'),toolbelt=$('#toolbelt'),toolScroll=$('#toolScroll'),shade=$('#shade'),nextPeek=$('#nextPeek'),nextPanel=$('#nextPanel'),panelContext=$('#panelContext'),panelPrimary=$('#panelPrimary'),panelSecondary=$('#panelSecondary'),modal=$('#modal'),toast=$('#toast');
const levels=[90,95,100,110,120,130,140,150];
const tokenMap={90:[.90,.90,.92,.90,.95],95:[.95,.95,.96,.95,.97],100:[1,1,1,1,1],110:[1.10,1.08,1.08,1.07,1.04],120:[1.20,1.14,1.15,1.13,1.07],130:[1.30,1.20,1.22,1.19,1.10],140:[1.40,1.27,1.30,1.25,1.13],150:[1.50,1.34,1.38,1.32,1.16]};
let scaleIndex=Math.max(0,levels.indexOf(Number(storage.get('aion-v08-scale','100')||100)));if(scaleIndex<0)scaleIndex=2;
let current='home',pageNode=null,historyStack=[];let currentParams={};
const state={loggedIn:storage.get('aion-v08-auth','in')!=='out',pinned:JSON.parse(storage.get('aion-v08-pinned','[]')||'[]'),workspace:storage.get('aion-v08-workspace','graphite')||'graphite',dim:Number(storage.get('aion-v08-dim','0.02')||0.02),depth:Number(storage.get('aion-v08-depth','1')||1),context:{client:'',device:'',service:'',part:'',supplier:'',order:''},order:{diagnosticsDone:true,approved:false,repairDone:false,sentOtk:false,otkPassed:false,otkProblem:false,total:12500,paid:10000,payment:'partial',issued:false},documents:{intake:true,approval:false,repair:false,final:false}};
const menu=[['clients','i-user','Клиенты'],['orders','i-clipboard','Заказы'],['stock','i-box','Склад'],['services','i-tag','Прайс'],['suppliers','i-cart','Поставщики'],['documents','i-doc','Документы'],['finance','i-money','Финансы'],['reports','i-chart','Отчёты'],['history','i-history','История'],['settings','i-gear','Настройки']];
const titleMap={home:'',search:'Поиск',capture:'Контекст',draft:'Новый ремонт',client:'Клиент',device:'Устройство',service:'Услуга',part:'Деталь',supplier:'Поставщик',orders:'Заказы',order:'Заказ №125',diagnostics:'Диагностика',approval:'Согласование',repair:'Ремонт',otk:'Контроль качества',payment:'Оплата',issue:'Выдача',documents:'Документы',clients:'Клиенты',stock:'Склад',services:'Прайс',suppliers:'Поставщики',finance:'Финансы',reports:'Отчёты',history:'История',settings:'Настройки'};
function ico(id){return `<svg class="ico"><use href="#${id}"/></svg>`}
function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1400)}
function openModal(html){modal.innerHTML=html;modal.classList.add('open');shade.classList.add('on')}
function closeModal(){modal.classList.remove('open');if(!toolbelt.classList.contains('open')&&!nextPanel.classList.contains('open'))shade.classList.remove('on')}
function applyWorkspace(){app.classList.remove('workspace-graphite','workspace-slate','workspace-ocean');app.classList.add('workspace-'+state.workspace);app.style.setProperty('--workspace-dim',String(state.dim));document.documentElement.style.setProperty('--depth',state.depth)}
function applyScale(index){scaleIndex=Math.max(0,Math.min(levels.length-1,index));const p=levels[scaleIndex],t=tokenMap[p];document.documentElement.style.setProperty('--text-scale',t[0]);document.documentElement.style.setProperty('--icon-scale',t[1]);document.documentElement.style.setProperty('--control-scale',t[2]);document.documentElement.style.setProperty('--space-scale',t[3]);document.documentElement.style.setProperty('--radius-scale',t[4]);app.dataset.scale=String(p);storage.set('aion-v08-scale',String(p));renderSettingsBar();renderHeader();updateNextAction();}
function renderSettingsBar(){const p=levels[scaleIndex];settingsBar.innerHTML=`<button data-set="minus">A−</button><button class="scale-readout" data-set="reset">${p}%</button><button data-set="plus">A+</button><button data-set="reset">100%</button><button data-set="theme" aria-label="Тема">◐</button><button data-set="workspace" aria-label="My Workspace">${ico('i-palette')}</button><button data-set="account" aria-label="Аккаунт">${ico('i-user')}</button>`}
function renderHeader(){const home=current==='home';header.classList.toggle('nested',!home&&state.loggedIn);headLeft.innerHTML=!state.loggedIn?'':home?`<button class="head-btn" data-head="menu" aria-label="Разделы"><span class="hamb"><i></i><i></i><i></i></span></button>`:`<button class="head-btn" data-head="back" aria-label="Назад">${ico('i-back')}</button><button class="head-btn" data-head="home" aria-label="На Главную">${ico('i-home')}</button>`;headerTitle.textContent=home?'':(titleMap[current]||'AION Service');app.classList.toggle('logged-out',!state.loggedIn)}
function routeRoot(route){return({client:'clients',device:'clients',service:'services',part:'stock',supplier:'suppliers',diagnostics:'orders',approval:'orders',repair:'orders',otk:'orders',payment:'orders',issue:'orders',order:'orders'}[route]||route)}
function renderToolbelt(){const root=routeRoot(current);toolScroll.innerHTML=menu.map(m=>`<button class="tool-item ${root===m[0]?'current':''} ${state.pinned.includes(m[0])?'pinned':''}" data-tool="${m[0]}">${ico(m[1])}<span>${m[2]}</span><i class="pin-dot" data-pin="${m[0]}">${state.pinned.includes(m[0])?'✓':'+'}</i></button>`).join('')}
function savePinned(){storage.set('aion-v08-pinned',JSON.stringify(state.pinned));renderToolbelt();if(current==='home')rerender('home')}
function toggleToolbelt(force){const open=force!==undefined?force:!toolbelt.classList.contains('open');toolbelt.classList.toggle('open',open);shade.classList.toggle('on',open||modal.classList.contains('open')||nextPanel.classList.contains('open'))}
function setNextPanel(open){if(open&&!navAction())return;nextPanel.classList.toggle('open',open);shade.classList.toggle('on',open||toolbelt.classList.contains('open')||modal.classList.contains('open'))}
function navAction(){if(!state.loggedIn)return null;const o=state.order;const operational=['approval','repair','otk','payment','issue'];if(operational.includes(current)&&currentParams.orderId&&currentParams.orderId!=='125')return null;if(current==='draft')return{label:'Создать ремонт',context:'Контекст сохранён. Создадим ремонт без выбора внутренних сущностей.',act:'create-repair'};if(current==='diagnostics')return{label:'Завершить диагностику',context:'После фиксации результата следующим станет согласование.',act:'finish-diagnostics'};if(current==='approval')return{label:'Согласовать 3 500 ₽',context:'Клиент: Иван Иванов · iPhone 13',act:'approve'};if(current==='repair')return{label:'Завершить ремонт',context:'Работы выполнены — зафиксируйте завершение.',act:'finish-repair'};if(current==='order'){if(!o.approved)return{label:'Согласовать 3 500 ₽',context:'Диагностика завершена. Нужно решение клиента.',go:'approval',secondary:'Документы'};if(!o.repairDone)return{label:'Начать ремонт',context:'Согласование подтверждено.',go:'repair',secondary:'Документы'};if(!o.sentOtk)return{label:'Передать на ОТК',context:'Ремонт завершён. Нужен независимый контроль качества.',act:'send-otk',secondary:'Документы'};if(!o.otkPassed)return{label:'Провести ОТК',context:'Заказ передан независимому проверяющему.',go:'otk',secondary:'Документы'};if(o.paid<o.total)return{label:'Принять 2 500 ₽',context:'ОТК пройден. Остался баланс 2 500 ₽.',go:'payment',secondary:'Документы'};if(!o.issued)return{label:'Выдать клиенту',context:'ОТК и оплата подтверждены.',go:'issue',secondary:'Документы'};return{label:'Открыть документы',context:'Устройство выдано. Финальные документы доступны.',go:'documents'};}if(current==='otk'){if(!o.otkPassed)return{label:'✓ ОТК пройден',context:'Обычный успешный контроль — одно подтверждение независимым проверяющим.',act:'otk-pass',secondary:'Есть проблема'};return{label:'Принять 2 500 ₽',context:'ОТК подтверждён. Проверил: Анна Смирнова.',go:'payment'};}if(current==='payment'){if(o.payment==='checking')return{label:'Проверяем результат оплаты…',context:'Не повторяйте операцию. Выполняется authoritative reread.',disabled:true};if(o.paid<o.total)return{label:'Принять 2 500 ₽',context:'Итого 12 500 ₽ · оплачено 10 000 ₽ · осталось 2 500 ₽',act:'accept-payment'};return{label:'Выдать клиенту',context:'Оплата подтверждена авторитетным источником.',go:'issue'};}if(current==='issue'){if(!o.otkPassed)return{label:'Провести ОТК',context:'Выдача заблокирована: контроль качества не подтверждён.',go:'otk'};if(o.paid<o.total)return{label:'Принять 2 500 ₽',context:'Выдача заблокирована: осталось оплатить 2 500 ₽.',go:'payment',secondary:'Документы'};if(!o.issued)return{label:'Выдать клиенту',context:'Все условия выдачи подтверждены.',act:'issue'};return{label:'Открыть документы',context:'Выдача зарегистрирована.',go:'documents'};}if(current==='client')return{label:'Открыть ремонт №125',context:'Сейчас: iPhone 13 · требуется согласование.',go:'order'};return null}
function updateNextAction(){const n=navAction();if(!n){nextPeek.classList.add('hidden');setNextPanel(false);return}nextPeek.classList.remove('hidden');$('#peekLabel').textContent='Следующее: '+n.label;panelContext.textContent=n.context;panelPrimary.textContent=n.label;panelPrimary.disabled=!!n.disabled;panelPrimary.dataset.action=n.act||'';panelPrimary.dataset.go=n.go||'';panelSecondary.textContent=n.secondary||'';panelSecondary.style.display=n.secondary?'block':'none';panelSecondary.dataset.secondary=n.secondary||''}