// v0.8 Start Anywhere completion: expose secondary repair start from existing operational context without competing with the local primary action.
const __orderScreenV08=screens.order;
screens.order=()=>__orderScreenV08().replace('data-go="device">Устройство</button></div></section>','data-go="device">Устройство</button><button class="small-btn ghost" data-new="order">Новый ремонт</button></div></section>');
const __documentsScreenV08=screens.documents;
screens.documents=()=>__documentsScreenV08()+`<button class="small-btn ghost context-new" data-new="order">Новый ремонт из контекста заказа</button>`;
const __historyScreenV08=screens.history;
screens.history=()=>__historyScreenV08()+`<button class="small-btn ghost context-new" data-new="order">Новый ремонт из истории</button>`;
document.addEventListener('click',e=>{const why=e.target.closest('[data-why]');if(why){e.preventDefault();e.stopPropagation();openModal(`<h3>Почему?</h3><p>Заказ №125 ждёт согласования дольше обычного. Факт: диагностика завершена в 09:10. Источник: журнал заказа. Рекомендация AION: связаться с клиентом. AION не изменяет статус.</p><div class="inline-actions"><button class="small-btn" data-close-modal>Закрыть</button></div>`);return}const debt=e.target.closest('[data-debt]');if(debt){openModal(`<h3>Выдача в долг — исключение</h3><p><b>Это НЕ оплата.</b> В production такой сценарий требует отдельного разрешения, основания, автора, времени и evidence. В этом v0.8 он только объясняется и не обходится одним toggle.</p><div class="inline-actions"><button class="small-btn" data-close-modal>Понятно</button></div>`);return}if(e.target.closest('[data-close-modal]')){closeModal();return}const pin=e.target.closest('[data-pin]');if(pin){e.preventDefault();e.stopPropagation();const id=pin.dataset.pin;state.pinned=state.pinned.includes(id)?state.pinned.filter(x=>x!==id):[...state.pinned,id].slice(-4);savePinned();return}const tool=e.target.closest('[data-tool]');if(tool){navigate(tool.dataset.tool);return}const cap=e.target.closest('[data-capture]');if(cap){e.preventDefault();e.stopPropagation();navigate('capture',{params:{mode:cap.dataset.capture}});return}const g=e.target.closest('[data-go]');if(g){e.preventDefault();navigate(g.dataset.go);return}const n=e.target.closest('[data-new]');if(n){newRepair(n.dataset.new);return}const f=e.target.closest('[data-fill]');if(f){fillContext(f.dataset.fill);return}const conf=e.target.closest('[data-confirm-match]');if(conf){navigate(conf.dataset.confirmMatch);return}const s=e.target.closest('[data-search]');if(s){const q=($('#searchInput')?.value||'').trim();if(/125|Иван/.test(q)){showToast('Однозначный заказ найден');setTimeout(()=>navigate('order'),180)}else navigate('capture',{params:{mode:'context'}});return}const set=e.target.closest('[data-set]');if(set){const a=set.dataset.set;if(a==='minus')applyScale(scaleIndex-1);if(a==='plus')applyScale(scaleIndex+1);if(a==='reset')applyScale(2);if(a==='theme')app.classList.toggle('light');if(a==='workspace')navigate('settings');return}const ws=e.target.closest('[data-workspace]');if(ws){state.workspace=ws.dataset.workspace;storage.set('aion-v08-workspace',state.workspace);applyWorkspace();rerender('settings');return}const doc=e.target.closest('[data-doc]');if(doc){showToast(doc.dataset.doc==='print'?'Печать доступна в capability-режиме':doc.dataset.doc==='download'?'Документ подготовлен к скачиванию':'Документ открыт');return}});
headLeft.addEventListener('click',e=>{const b=e.target.closest('[data-head]');if(!b)return;if(b.dataset.head==='menu')toggleToolbelt();if(b.dataset.head==='back')goBack();if(b.dataset.head==='home')goHome()});gearBtn.addEventListener('click',()=>settingsBar.classList.toggle('open'));settingsBar.addEventListener('click',e=>{const b=e.target.closest('[data-set]');if(!b)return;e.preventDefault();e.stopPropagation();const a=b.dataset.set;if(a==='minus')applyScale(scaleIndex-1);if(a==='plus')applyScale(scaleIndex+1);if(a==='reset')applyScale(2);if(a==='theme')app.classList.toggle('light');if(a==='workspace')navigate('settings')});$('#toolTrigger').addEventListener('click',()=>toggleToolbelt());shade.addEventListener('click',()=>{toggleToolbelt(false);setNextPanel(false);closeModal()});nextPeek.addEventListener('click',()=>setNextPanel(true));panelPrimary.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(panelPrimary.disabled)return;if(panelPrimary.dataset.action)act(panelPrimary.dataset.action);else if(panelPrimary.dataset.go)navigate(panelPrimary.dataset.go)});panelSecondary.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(panelSecondary.dataset.secondary==='Документы')navigate('documents');if(panelSecondary.dataset.secondary==='Есть проблема'){state.order.otkProblem=true;rerender('otk')}});
let edgeStart=null;app.addEventListener('touchstart',e=>{const p=e.touches[0];edgeStart={x:p.clientX,y:p.clientY}},{passive:true});app.addEventListener('touchend',e=>{if(!edgeStart)return;const p=e.changedTouches[0],dx=p.clientX-edgeStart.x,dy=p.clientY-edgeStart.y;if(edgeStart.x<24&&dx>55&&Math.abs(dy)<50&&!toolbelt.classList.contains('open'))goBack();edgeStart=null},{passive:true});
const review=new URLSearchParams(location.search);const qScale=Number(review.get('scale'));if(levels.includes(qScale))scaleIndex=levels.indexOf(qScale);const qWorkspace=review.get('workspace');if(['graphite','slate','ocean'].includes(qWorkspace))state.workspace=qWorkspace;applyWorkspace();applyScale(scaleIndex);renderSettingsBar();renderToolbelt();navigate(review.get('screen')&&screens[review.get('screen')]?review.get('screen'):'home',{home:true});if(review.get('rail')==='1')setTimeout(()=>toggleToolbelt(true),250);if(review.get('next')==='1')setTimeout(()=>setNextPanel(true),250);
