const $=(s,r=document)=>r.querySelector(s);
const app=$('#app'),stage=$('#stage'),sysLeft=$('#sysLeft'),sysTitle=$('#sysTitle'),controlsBtn=$('#controlsBtn'),drawer=$('#drawer'),drawerScroll=$('#drawerScroll'),backdrop=$('#backdrop'),popover=$('#controlPopover'),dock=$('#actionDock'),dockAction=$('#dockAction'),sheet=$('#actionSheet'),sheetTitle=$('#sheetTitle'),sheetText=$('#sheetText'),sheetPrimary=$('#sheetPrimary'),sheetDocs=$('#sheetDocs'),toast=$('#toast');
const icons={menu:'i-menu',home:'i-house',plus:'i-plus',search:'i-search',scan:'i-scan',camera:'i-camera',mic:'i-mic',users:'i-users',orders:'i-orders',package:'i-package',tags:'i-tags',truck:'i-truck',wallet:'i-wallet',doc:'i-doc',chart:'i-chart',history:'i-history',back:'i-back',chev:'i-chevron'};
const svg=n=>`<svg class="ico"><use href="#${icons[n]||n}"/></svg>`;
const modules=[['clients','users','Клиенты'],['orders','orders','Заказы'],['stock','package','Склад'],['price','tags','Прайс'],['suppliers','truck','Поставщики'],['finance','wallet','Финансы'],['documents','doc','Документы'],['reports','chart','Отчёты'],['history','history','История']];
let route='home',page=null,historyStack=[],scale=100,theme='dark',workspace='graphite';
const state={approved:false};
function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1300)}
function setRuntimeBottom(){const vv=window.visualViewport;let obstruction=0;if(vv){obstruction=Math.max(0,window.innerHeight-vv.height-vv.offsetTop)}document.documentElement.style.setProperty('--runtime-bottom',`${Math.round(obstruction)}px`)}
setRuntimeBottom();window.visualViewport?.addEventListener('resize',setRuntimeBottom);window.visualViewport?.addEventListener('scroll',setRuntimeBottom);window.addEventListener('resize',setRuntimeBottom);
function header(){const home=route==='home';sysLeft.innerHTML=home?`<button class="sys-icon brand-menu pressable" data-head="menu" aria-label="Разделы">${svg('menu')}</button>`:`<button class="sys-icon pressable" data-head="back" aria-label="Назад">${svg('back')}</button><button class="sys-icon pressable" data-head="home" aria-label="Рабочий стол">${svg('home')}</button>`;sysTitle.textContent=home?'':route==='order'?'Заказ №125':route==='new'?'Новый ремонт':route==='search'?'Поиск':'AION Service'}
function attentionRow(num,device,action,status,klass,extra=''){return `<button class="attention-row" data-route="order"><span class="attention-main"><strong>№${num} · ${device}</strong><span>${action}</span>${extra?`<small>${extra}</small>`:''}</span><span class="status-chip ${klass}">${status}</span></button>`}
function homeScreen(){return `<div class="content"><section class="hero"><h1>AION Service</h1><p>Добрый вечер, Иван</p></section><section class="work-surface attention"><div class="attention-head">Требует внимания</div>${attentionRow('125','iPhone 13','Нужно согласование','Просрочено','overdue','AION: клиент ждёт дольше обычного · <span class="ai-why">Почему?</span>')}${attentionRow('128','iPhone 14','Продолжить ремонт','Деталь получена','part')}${attentionRow('124','iPhone 13','Передать на ОТК','Независимый','qc')}</section><section class="home-actions"><button class="primary-row" data-route="new"><span class="action-icon">${svg('plus')}</span><span class="action-copy"><strong>Новый ремонт</strong><small>Создать заказ</small></span><span class="chev">${svg('chev')}</span></button><button class="search-row" data-route="search"><span class="action-icon">${svg('search')}</span><span class="action-copy"><strong>Найти что угодно</strong><small>Заказ · клиент · устройство</small></span><span></span><span class="search-tools"><span class="quick-tool" data-capture="qr">${svg('scan')} QR</span><span class="quick-tool" data-capture="photo">${svg('camera')} Фото</span><span class="quick-tool" data-capture="voice">${svg('mic')} Голос</span></span></button></section></div>`}
function orderScreen(){const current=state.approved?'Согласование подтверждено':'Диагностика завершена';const required=state.approved?'Начать ремонт':'Согласование клиента';const blocker=state.approved?'Нет блокировки':'Ремонт нельзя продолжить';return `<div class="content"><section class="work-surface order-hero"><h1>Заказ №125</h1><p>iPhone 13 · Иван Иванов</p><div class="truth-stack"><div class="truth-item active"><label>СЕЙЧАС</label><strong>${current}</strong></div><div class="truth-item"><label>ТРЕБУЕТ</label><strong>${required}</strong></div><div class="truth-item blocker"><label>БЛОКИРУЕТ</label><strong>${blocker}</strong></div></div></section><div class="secondary-links"><button class="secondary-link" data-placeholder="Документы">Документы</button><button class="secondary-link" data-placeholder="Клиент">Клиент</button><button class="secondary-link" data-placeholder="Устройство">Устройство</button></div></div>`}
function placeholder(title,text){return `<div class="content"><section class="work-surface placeholder"><h1>${title}</h1><p>${text}</p></section></div>`}
const renderers={home:homeScreen,order:orderScreen,new:()=>placeholder('Новый ремонт','Рабочая поверхность следующего шага. Checkpoint 01 проверяет только визуальный и interaction DNA.'),search:()=>placeholder('Найти что угодно','Единый поиск CRM: заказ, клиент или устройство. Полный search-flow будет после Owner DNA Gate.')};
function renderRoute(r){return (renderers[r]||(()=>placeholder('AION Service','Раздел доступен из навигации. Детальная реализация — после DNA approval.')))()}
function setDock(){if(route!=='order'){dock.classList.add('hidden');closeSheet(false);return}dock.classList.remove('hidden');dockAction.textContent=state.approved?'Начать ремонт':'Согласовать 3 500 ₽';sheetTitle.textContent=state.approved?'Согласование подтверждено':'Диагностика завершена';sheetText.textContent=state.approved?'Следующее безопасное действие — начать ремонт.':'Нужно согласовать 3 500 ₽ с клиентом.';sheetPrimary.textContent=state.approved?'Начать ремонт':'Согласовать 3 500 ₽'}
function navigate(next,mode='forward'){if(next===route&&page)return;closeDrawer();closePopover();closeSheet(false);const old=page;if(mode==='forward'&&route!==next)historyStack.push(route);route=next;const n=document.createElement('section');n.className=`page enter-${mode}`;n.innerHTML=renderRoute(route);stage.appendChild(n);page=n;header();setDock();requestAnimationFrame(()=>{n.classList.remove(`enter-${mode}`);if(old){old.classList.add(`exit-${mode}`);setTimeout(()=>old.remove(),290)}})}
function goBack(){if(!historyStack.length)return navigate('home','home');const prev=historyStack.pop();navigateWithoutPush(prev,'back')}
function navigateWithoutPush(next,mode){closeDrawer();closePopover();closeSheet(false);const old=page;route=next;const n=document.createElement('section');n.className=`page enter-${mode}`;n.innerHTML=renderRoute(route);stage.appendChild(n);page=n;header();setDock();requestAnimationFrame(()=>{n.classList.remove(`enter-${mode}`);if(old){old.classList.add(`exit-${mode}`);setTimeout(()=>old.remove(),285)}})}
function goHome(){historyStack=[];navigateWithoutPush('home','home')}
function renderDrawer(){drawerScroll.innerHTML=modules.map(([id,ic,label])=>`<button class="module-item ${id==='orders'&&route==='order'?'current':''}" data-module="${id}">${svg(ic)}<span>${label}</span></button>`).join('')}
function openDrawer(){renderDrawer();drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');backdrop.classList.add('on');app.classList.add('depth')}
function closeDrawer(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');if(!sheet.classList.contains('open')&&!popover.classList.contains('open'))backdrop.classList.remove('on');if(!sheet.classList.contains('open')&&!popover.classList.contains('open'))app.classList.remove('depth')}
function renderPopover(){popover.innerHTML=`<div class="control-row"><button class="control-btn pressable" data-scale="minus">A−</button><button class="control-btn control-value pressable" data-scale="reset">${scale}%</button><button class="control-btn pressable" data-scale="plus">A+</button></div><button class="control-item pressable" data-control="theme"><span>Тема</span><strong>${theme==='dark'?'Тёмная':'Светлая'}</strong></button><button class="control-item pressable" data-control="workspace"><span>My Workspace</span><strong>${workspace==='graphite'?'Graphite':'Ocean'}</strong></button><button class="control-item pressable" data-control="account"><span>Аккаунт</span><strong>Иван</strong></button>`}
function openPopover(){renderPopover();popover.classList.add('open');popover.setAttribute('aria-hidden','false');backdrop.classList.add('on');app.classList.add('depth')}
function closePopover(){popover.classList.remove('open');popover.setAttribute('aria-hidden','true');if(!drawer.classList.contains('open')&&!sheet.classList.contains('open'))backdrop.classList.remove('on');if(!drawer.classList.contains('open')&&!sheet.classList.contains('open'))app.classList.remove('depth')}
function openSheet(){if(route!=='order')return;sheet.classList.add('open');sheet.setAttribute('aria-hidden','false');backdrop.classList.add('on');app.classList.add('depth')}
function closeSheet(clearDepth=true){sheet.classList.remove('open');sheet.setAttribute('aria-hidden','true');if(!drawer.classList.contains('open')&&!popover.classList.contains('open'))backdrop.classList.remove('on');if(clearDepth&&!drawer.classList.contains('open')&&!popover.classList.contains('open'))app.classList.remove('depth')}
function rerender(){if(!page)return;const scroll=page.scrollTop;page.innerHTML=renderRoute(route);page.scrollTop=scroll;header();setDock()}
document.addEventListener('click',e=>{const head=e.target.closest('[data-head]');if(head){head.dataset.head==='menu'?openDrawer():head.dataset.head==='back'?goBack():goHome();return}const go=e.target.closest('[data-route]');if(go){navigate(go.dataset.route);return}const cap=e.target.closest('[data-capture]');if(cap){e.preventDefault();e.stopPropagation();navigate('search');showToast(cap.dataset.capture==='qr'?'QR capture':cap.dataset.capture==='photo'?'Фото capture':'Голосовой ввод');return}const mod=e.target.closest('[data-module]');if(mod){const id=mod.dataset.module;if(id==='orders')navigate('order');else{closeDrawer();showToast(`${mod.textContent.trim()} — после DNA Gate`)}return}const ph=e.target.closest('[data-placeholder]');if(ph){showToast(`${ph.dataset.placeholder} — следующий checkpoint`);return}const sc=e.target.closest('[data-scale]');if(sc){scale=sc.dataset.scale==='minus'?Math.max(90,scale-10):sc.dataset.scale==='plus'?Math.min(120,scale+10):100;document.documentElement.style.fontSize=`${scale}%`;renderPopover();return}const ctl=e.target.closest('[data-control]');if(ctl){if(ctl.dataset.control==='theme'){theme=theme==='dark'?'light':'dark';app.classList.toggle('theme-light',theme==='light')}else if(ctl.dataset.control==='workspace'){workspace=workspace==='graphite'?'ocean':'graphite';app.classList.toggle('workspace-ocean',workspace==='ocean')}else showToast('Иван · Мастер');renderPopover();return}});
controlsBtn.addEventListener('click',()=>popover.classList.contains('open')?closePopover():openPopover());backdrop.addEventListener('click',()=>{closeDrawer();closePopover();closeSheet()});dock.addEventListener('click',openSheet);sheetDocs.addEventListener('click',()=>showToast('Документы — следующий checkpoint'));sheetPrimary.addEventListener('click',()=>{if(!state.approved){state.approved=true;closeSheet();showToast('Согласование подтверждено');rerender()}else{closeSheet();showToast('Следующий flow — после DNA Gate')}});
let sheetStart=null,drawerStart=null,edgeStart=null;sheet.addEventListener('touchstart',e=>{const p=e.touches[0];sheetStart={x:p.clientX,y:p.clientY}},{passive:true});sheet.addEventListener('touchend',e=>{if(!sheetStart)return;const p=e.changedTouches[0];if(p.clientY-sheetStart.y>45)closeSheet();sheetStart=null},{passive:true});drawer.addEventListener('touchstart',e=>{const p=e.touches[0];drawerStart={x:p.clientX,y:p.clientY}},{passive:true});drawer.addEventListener('touchend',e=>{if(!drawerStart)return;const p=e.changedTouches[0];if(p.clientX-drawerStart.x>42)closeDrawer();drawerStart=null},{passive:true});app.addEventListener('touchstart',e=>{const p=e.touches[0];edgeStart={x:p.clientX,y:p.clientY}},{passive:true});app.addEventListener('touchend',e=>{if(!edgeStart)return;const p=e.changedTouches[0],dx=p.clientX-edgeStart.x,dy=p.clientY-edgeStart.y;if(Math.abs(dy)<55){if(edgeStart.x>window.innerWidth-22&&dx<-52&&!sheet.classList.contains('open'))openDrawer();else if(edgeStart.x<22&&dx>52&&!drawer.classList.contains('open'))goBack()}edgeStart=null},{passive:true});
header();renderDrawer();navigateWithoutPush('home','home');
